-- ============================================================================
-- FN Hub CONTROL PLANE -- per-nation support-login signing keys (asymmetric).
-- Runs on the "fnhub-platform" project. Super-admins only. Run in the platform
-- SQL Editor.
--
-- Each nation gets its OWN ES256 (ECDSA P-256) keypair:
--   * private_jwk lives ONLY here (the control plane) -- enter-nation signs a
--     short-lived entry token with it.
--   * public_jwk is ALSO shown here so the operator can copy it into that
--     nation's SUPPORT_LOGIN_PUBKEY Edge Function secret, where support-login
--     verifies the token. A stolen public key cannot forge a token, so a leak of
--     one nation's stored material grants nothing -- and no shared secret means
--     no "leak anywhere = access everywhere".
--
-- The keypair is generated by the `gen-support-key` Edge Function (server-side;
-- the private key never touches a browser) and is LOCKED once set: regenerating
-- requires an explicit rotate, which invalidates the nation's current public key
-- until it is re-copied.
-- ============================================================================
create table if not exists public.nation_support_keys (
  subdomain    text primary key references public.nations(subdomain) on delete cascade,
  algorithm    text not null default 'ES256',
  private_jwk  jsonb not null,      -- control-plane ONLY; never sent to a browser
  public_jwk   jsonb not null,      -- safe to display/copy; set on the nation project
  created_by   text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

alter table public.nation_support_keys enable row level security;
drop policy if exists nation_support_keys_all on public.nation_support_keys;
create policy nation_support_keys_all on public.nation_support_keys for all
  using (public.is_super_admin()) with check (public.is_super_admin());

-- Public-only view so the admin panel reads status WITHOUT ever selecting the
-- private key. security_invoker=true makes it honor the base table's RLS, so it
-- stays super-admin-only (not a bypass). The private_jwk is read solely by the
-- enter-nation function via the service role.
create or replace view public.nation_support_keys_public
  with (security_invoker = true) as
  select subdomain, algorithm, public_jwk, created_by, created_at, updated_at
  from public.nation_support_keys;

grant select on public.nation_support_keys_public to authenticated;
