with
ext as (
  select 1 as sec,
         quote_ident(e.extname)::text as nm,
         ('create extension if not exists ' || quote_ident(e.extname) ||
          ' with schema ' || quote_ident(n.nspname) || ';')::text as ddl
    from pg_extension e
    join pg_namespace n on n.oid = e.extnamespace
   where e.extname <> 'plpgsql'
),
seqs as (
  select 2 as sec,
         c.relname::text as nm,
         ('create sequence if not exists public.' || quote_ident(c.relname) ||
          ' as ' || s.data_type::text ||
          ' increment by ' || s.increment_by ||
          ' minvalue ' || s.min_value ||
          ' maxvalue ' || s.max_value ||
          ' start with ' || s.start_value ||
          ' cache ' || s.cache_size ||
          case when s.cycle then ' cycle' else ' no cycle' end || ';')::text as ddl
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    join pg_sequences s on s.schemaname = n.nspname and s.sequencename = c.relname
   where n.nspname = 'public'
     and c.relkind = 'S'
     and not exists (select 1 from pg_depend d
                      where d.objid = c.oid and d.deptype = 'i')
),
tbls as (
  select 3 as sec,
         c.relname::text as nm,
         ('create table if not exists public.' || quote_ident(c.relname) || ' (' || chr(10) ||
          string_agg(
            '  ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
            || case
                 when a.attgenerated = 's'
                   then ' generated always as (' || pg_get_expr(ad.adbin, ad.adrelid) || ') stored'
                 when a.attidentity = 'a' then ' generated always as identity'
                 when a.attidentity = 'd' then ' generated by default as identity'
                 else coalesce(' default ' || pg_get_expr(ad.adbin, ad.adrelid), '')
               end
            || case when a.attnotnull then ' not null' else '' end,
            ',' || chr(10) order by a.attnum)
          || chr(10) || ');')::text as ddl
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
    left join pg_attrdef ad on ad.adrelid = c.oid and ad.adnum = a.attnum
   where n.nspname = 'public'
     and c.relkind in ('r','p')
     and not exists (select 1 from pg_depend d
                      where d.objid = c.oid and d.deptype = 'e')
   group by c.relname
),
cons_pk as (
  select 4 as sec,
         (c.relname || '.' || con.conname)::text as nm,
         ('alter table public.' || quote_ident(c.relname) ||
          ' add constraint ' || quote_ident(con.conname) || ' ' ||
          pg_get_constraintdef(con.oid) || ';')::text as ddl
    from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public'
     and con.contype in ('p','u')
),
cons_fk as (
  select 5 as sec,
         (c.relname || '.' || con.conname)::text as nm,
         ('alter table public.' || quote_ident(c.relname) ||
          ' add constraint ' || quote_ident(con.conname) || ' ' ||
          pg_get_constraintdef(con.oid) || ';')::text as ddl
    from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public'
     and con.contype in ('c','f')
     and con.conislocal
),
idxs as (
  select 6 as sec,
         i.indexname::text as nm,
         (i.indexdef || ';')::text as ddl
    from pg_indexes i
   where i.schemaname = 'public'
     and not exists (
       select 1
         from pg_constraint con
         join pg_class ci on ci.oid = con.conindid
         join pg_namespace cn on cn.oid = con.connamespace
        where cn.nspname = 'public'
          and ci.relname = i.indexname)
),
fns as (
  select 7 as sec,
         (p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')')::text as nm,
         (pg_get_functiondef(p.oid) || ';')::text as ddl
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public'
     and p.prokind in ('f','p')
     and not exists (select 1 from pg_depend d
                      where d.objid = p.oid and d.deptype = 'e')
),
trgs as (
  select 8 as sec,
         (c.relname || '.' || t.tgname)::text as nm,
         (pg_get_triggerdef(t.oid) || ';')::text as ddl
    from pg_trigger t
    join pg_class c on c.oid = t.tgrelid
    join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public'
     and not t.tgisinternal
),
vws as (
  select 9 as sec,
         c.relname::text as nm,
         (case c.relkind
            when 'v' then 'create or replace view public.'
            else 'create materialized view if not exists public.'
          end || quote_ident(c.relname) || ' as' || chr(10) ||
          pg_get_viewdef(c.oid, true))::text as ddl
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public'
     and c.relkind in ('v','m')
),
rls as (
  select 10 as sec,
         c.relname::text as nm,
         ('alter table public.' || quote_ident(c.relname) ||
          ' enable row level security;' ||
          case when c.relforcerowsecurity
               then chr(10) || 'alter table public.' || quote_ident(c.relname) ||
                    ' force row level security;'
               else '' end)::text as ddl
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public'
     and c.relkind = 'r'
     and c.relrowsecurity
),
pols as (
  select 11 as sec,
         (p.schemaname || '.' || p.tablename || '.' || p.policyname)::text as nm,
         ('create policy ' || quote_ident(p.policyname) ||
          ' on ' || quote_ident(p.schemaname) || '.' || quote_ident(p.tablename) ||
          ' as ' || p.permissive ||
          ' for ' || p.cmd ||
          ' to ' || array_to_string(p.roles, ', ') ||
          coalesce(' using (' || p.qual || ')', '') ||
          coalesce(' with check (' || p.with_check || ')', '') || ';')::text as ddl
    from pg_policies p
   where p.schemaname in ('public','storage')
),
grnts as (
  select 12 as sec,
         (g.table_name || '.' || g.grantee)::text as nm,
         ('grant ' || string_agg(distinct lower(g.privilege_type), ', ') ||
          ' on public.' || quote_ident(g.table_name) ||
          ' to ' || quote_ident(g.grantee) || ';')::text as ddl
    from information_schema.role_table_grants g
   where g.table_schema = 'public'
     and g.grantee in ('anon','authenticated','service_role')
   group by g.table_name, g.grantee
),
seq_owned as (
  select 13 as sec,
         s.relname::text as nm,
         ('alter sequence public.' || quote_ident(s.relname) ||
          ' owned by public.' || quote_ident(c.relname) || '.' ||
          quote_ident(a.attname) || ';')::text as ddl
    from pg_class s
    join pg_namespace n on n.oid = s.relnamespace
    join pg_depend d on d.objid = s.oid and d.deptype = 'a'
    join pg_class c on c.oid = d.refobjid
    join pg_attribute a on a.attrelid = c.oid and a.attnum = d.refobjsubid
   where n.nspname = 'public'
     and s.relkind = 'S'
),
hdrs as (
  select  1 as sec, ''::text as nm, '-- ============ Extensions ============'::text as ddl
  union all select  2, ''::text, '-- ============ Sequences ============'::text
  union all select  3, ''::text, '-- ============ Tables ============'::text
  union all select  4, ''::text, '-- ============ Primary key / unique constraints ============'::text
  union all select  5, ''::text, '-- ============ Check / foreign key constraints ============'::text
  union all select  6, ''::text, '-- ============ Indexes ============'::text
  union all select  7, ''::text, '-- ============ Functions ============'::text
  union all select  8, ''::text, '-- ============ Triggers ============'::text
  union all select  9, ''::text, '-- ============ Views ============'::text
  union all select 10, ''::text, '-- ============ Row level security ============'::text
  union all select 11, ''::text, '-- ============ Policies ============'::text
  union all select 12, ''::text, '-- ============ Grants ============'::text
  union all select 13, ''::text, '-- ============ Sequence ownership ============'::text
),
all_ddl as (
  select * from hdrs
  union all select * from ext
  union all select * from seqs
  union all select * from tbls
  union all select * from cons_pk
  union all select * from cons_fk
  union all select * from idxs
  union all select * from fns
  union all select * from trgs
  union all select * from vws
  union all select * from rls
  union all select * from pols
  union all select * from grnts
  union all select * from seq_owned
)
select ddl
  from all_ddl
 order by sec, nm;
